{
  "log": {
    "disabled": true,
    "level": "warn",
    "timestamp": false
  },
  "experimental": {
    "clash_api": {
      "external_controller": "127.0.0.1:9090",
      "external_ui": "../files/yacd",
      "external_ui_download_url": "https://github.com/MetaCubeX/Yacd-meta/archive/gh-pages.zip",
      "external_ui_download_detour": "Friendly_Teams",
      "secret": "",
      "default_mode": "Rule"
    }
  },
  "dns": {
    "servers": [
      {
        "tag": "Friendly_Teams-dns",
        "address": "1.0.0.1",
        "strategy": "ipv4_only",
        "detour": "Friendly_Teams"
      },
      {
        "tag": "Best Latency-dns",
        "address": "1.1.1.1",
        "strategy": "ipv4_only",
        "detour": "Best Latency"
      },
      {
        "tag": "direct-dns",
        "address": "local",
        "strategy": "ipv4_only",
        "detour": "direct"
      },
      {
        "tag": "block-dns",
        "address": "rcode://success"
      }
    ],
    "rules": [
      {
        "domain": [],
        "domain_keyword": [],
        "domain_regex": [],
        "domain_suffix": [
          ".arpa.",
          ".arpa"
        ],
        "geosite": [
          "oisd-full",
          "oisd-nsfw"
        ],
        "server": "block-dns"
      },
      {
        "network": "udp",
        "port": 443,
        "server": "block-dns",
        "rewrite_ttl": 20
      },
      {
        "outbound": "Friendly_Teams",
        "server": "Friendly_Teams-dns",
        "rewrite_ttl": 20
      },
      {
        "outbound": "Best Latency",
        "server": "Best Latency-dns",
        "rewrite_ttl": 20
      },
      {
        "outbound": "direct",
        "server": "direct-dns",
        "rewrite_ttl": 20,
        "domain_suffix": [
          "dns.google.com"
        ]
      },
      {
        "outbound": "any",
        "server": "direct-dns",
        "rewrite_ttl": 20
      }
    ],
    "reverse_mapping": true,
    "strategy": "ipv4_only",
    "independent_cache": true
  },
  "inbounds": [
    {
      "type": "tun",
      "tag": "tun-in",
      "inet4_address": "172.19.0.1/30",
      "mtu": 9000,
      "auto_route": true,
      "strict_route": true,
      "stack": "system",
      "endpoint_independent_nat": true,
      "sniff": true
    },
    {
      "listen": "0.0.0.0",
      "listen_port": 6969,
      "sniff": true,
      "tag": "mixed-in",
      "type": "mixed"
    }
  ],
  "outbounds": [
    {
      "type": "selector",
      "tag": "Friendly_Teams",
      "outbounds": [
        "Best Latency",
        "(pribadi) [VLESS - ws] TLS ✅"
      ]
    },
    {
      "type": "urltest",
      "tag": "Best Latency",
      "outbounds": [
        "(pribadi) [VLESS - ws] TLS ✅"
      ],
      "url": "https://detectportal.firefox.com/success.txt",
      "interval": "5m0s"
    },
    {
      "type": "selector",
      "tag": "GAMES",
      "outbounds": [
        "direct",
        "(pribadi) [VLESS - ws] TLS ✅"
      ]
    },
    {
      "type": "selector",
      "tag": "STREAMING",
      "outbounds": [
        "direct",
        "(pribadi) [VLESS - ws] TLS ✅"
      ]
    },
    {
      "type": "selector",
      "tag": "SOSMED",
      "outbounds": [
        "direct",
        "(pribadi) [VLESS - ws] TLS ✅"
      ]
    },
    {
      "type": "selector",
      "tag": "ADS BLOCK",
      "outbounds": [
        "block",
        "(pribadi) [VLESS - ws] TLS ✅"
      ]
    },
    {
      "type": "vless",
      "tag": "(pribadi) [VLESS - ws] TLS ✅",
      "domain_strategy": "prefer_ipv6",
      "fallback_delay": "300ms",
      "server": "104.22.5.240",
      "server_port": 443,
      "uuid": "72aa3c86-2307-46ad-b80e-5bbb5b0b1169",
      "tls": {
        "enabled": true,
        "server_name": "id.lolicon.biz.id",
        "insecure": true,
        "utls": {
          "fingerprint": "chrome"
        }
      },
      "multiplex": {
        "enabled": false,
        "protocol": "smux",
        "max_streams": 32
      },
      "transport": {
        "type": "ws",
        "path": "/vless",
        "headers": {
          "Host": "id.lolicon.biz.id"
        },
        "max_early_data": 0,
        "early_data_header_name": "Sec-WebSocket-Protocol"
      }
    },
    {
      "type": "direct",
      "tag": "direct"
    },
    {
      "type": "block",
      "tag": "block"
    },
    {
      "type": "dns",
      "tag": "dns-out"
    }
  ],
  "route": {
    "auto_detect_interface": true,
    "override_android_vpn": true,
    "final": "Friendly_Teams",
    "geoip": {
      "download_url": "https://github.com/malikshi/sing-box-geo/releases/latest/download/geoip.db",
      "download_detour": "Friendly_Teams"
    },
    "geosite": {
      "download_url": "https://github.com/malikshi/v2ray-rules-dat/releases/latest/download/geosite.db",
      "download_detour": "Friendly_Teams"
    },
    "rules": [
      {
        "outbound": "dns-out",
        "port": [
          53
        ]
      },
      {
        "domain": [],
        "domain_keyword": [],
        "domain_regex": [],
        "domain_suffix": [],
        "geosite": [
          "rule-gaming"
        ],
        "outbound": "GAMES"
      },
      {
        "domain": [],
        "domain_keyword": [],
        "domain_regex": [],
        "domain_suffix": [],
        "geosite": [
          "rule-streaming"
        ],
        "outbound": "STREAMING"
      },
      {
        "domain": [],
        "domain_keyword": [],
        "domain_regex": [],
        "domain_suffix": [],
        "geosite": [
          "rule-sosmed"
        ],
        "outbound": "SOSMED"
      },
      {
        "domain": [],
        "domain_keyword": [],
        "domain_regex": [],
        "domain_suffix": [],
        "geosite": [
          "rule-ads"
        ],
        "outbound": "block"
      },
      {
        "domain": [],
        "domain_keyword": [],
        "domain_regex": [],
        "domain_suffix": [],
        "geosite": [
          "oisd-full"
        ],
        "outbound": "block"
      },
      {
        "domain": [],
        "domain_keyword": [],
        "domain_regex": [],
        "domain_suffix": [],
        "geosite": [
          "oisd-nsfw"
        ],
        "outbound": "block"
      },
      {
        "ip_cidr": [
          "224.0.0.0/3",
          "ff00::/8"
        ],
        "source_ip_cidr": [
          "224.0.0.0/3",
          "ff00::/8"
        ],
        "outbound": "block"
      }
    ]
  }
}
